<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title></title>
<style></style>
</head>
<body>
	<div class="wrapper">
		<div class="user-broke-promise">
		
			<div class="widget">
				<div class="widget-head">
					<h5>反欺诈规则查询结果</h5>
					<font color="red">注：空：未命中，0：本人直接命中，1：一度关系命中，2：二度关系命中</font>
				</div>
				<div class="widget-content">
					<table class="table table-striped table-bordered table-hover results">
						<thead>
						<tr>
							<th>类别</th>
							<th>通过身份证号查询</th>
							<th>通过手机号查询</th>
							<th>通过联系人手机查询</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<th>高危行为</th>
							<td>${sl_id_abnormal}</td>
							<td>${sl_cell_abnormal}</td>
							<td>${sl_lm_cell_abnormal}</td>
						</tr>
						<tr>
							<th>电信欠费</th>
							<td>${sl_id_phone_overdue}</td>
							<td>${sl_cell_phone_overdue}</td>
							<td>${sl_lm_cell_phone_overdue}</td>
							
						</tr>
						<tr>
							<th>法院失信人</th>
							<td>${sl_id_court_bad}</td>
							<td></td>
							<td></td>
							
						</tr>
						<tr>
							<th>法院被执行人</th>
							<td>${sl_id_court_executed}</td>
							<td></td>
							<td></td>
							
						</tr>
						<tr>
							<th>银行(含信用卡)中风险</th>
							<td>${sl_id_bank_bad}</td>
							<td>${sl_cell_bank_bad}</td>
							<td>${sl_lm_cell_bank_bad}</td>
							
						</tr>
						<tr>
							<th>银行(含信用卡)一般风险</th>
							<td>${sl_id_bank_overdue}</td>
							<td>${sl_cell_bank_overdue}</td>
							<td>${sl_lm_cell_bank_overdue}</td>
						</tr>
						<tr>
							<th>银行(含信用卡)资信不佳</th>
							<td>${sl_id_bank_fraud}</td>
							<td>${sl_cell_bank_fraud}</td>
							<td>${sl_lm_cell_bank_fraud}</td>
						</tr>
						<tr>
							<th>银行(含信用卡)高风险</th>
							<td>${sl_id_bank_lost}</td>
							<td>${sl_cell_bank_lost}</td>
							<td>${sl_lm_cell_bank_lost}</td>
						</tr>
						<tr>
							<th>银行(含信用卡)拒绝</th>
							<td>${sl_id_bank_refuse}</td>
							<td>${sl_cell_bank_refuse}</td>
							<td>${sl_lm_cell_bank_refuse}</td>
						</tr>
						<tr>
							<th>非银(含全部非银类型)中风险</th>
							<td>${sl_id_p2p_bad}</td>
							<td>${sl_cell_p2p_bad}</td>
							<td></td>
						</tr>
						<tr>
							<th>非银(含全部非银类型)一般风险</th>
							<td>${sl_id_p2p_overdue}</td>
							<td>${sl_cell_p2p_overdue}</td>
							<td></td>
						</tr>
						<tr>
							<th>非银(含全部非银类型)资信不佳</th>
							<td>${sl_id_p2p_fraud}</td>
							<td>${sl_cell_p2p_fraud}</td>
							<td></td>
						</tr>
						<tr>
							<th>非银(含全部非银类型)高风险</th>
							<td>${sl_id_p2p_lost}</td>
							<td>${sl_cell_p2p_lost}</td>
							<td></td>
						</tr>
						<tr>
							<th>非银(含全部非银类型)拒绝</th>
							<td>${sl_id_p2p_refuse}</td>
							<td>${sl_cell_p2p_refuse}</td>
							<td></td>
						</tr>
						<tr>
							<th>非银-P2P中风险</th>
							<td>${sl_id_nbank_p2p_bad}</td>
							<td>${sl_cell_nbank_p2p_bad}</td>
							<td>${sl_lm_cell_nbank_p2p_bad}</td>
						</tr>
						<tr>
							<th>非银-P2P一般风险</th>
							<td>${sl_id_nbank_p2p_overdue}</td>
							<td>${sl_cell_nbank_p2p_overdue}</td>
							<td>${sl_lm_cell_nbank_p2p_overdue}</td>
						</tr>
						<tr>
							<th>非银-P2P资信不佳</th>
							<td>${sl_id_nbank_p2p_fraud}</td>
							<td>${sl_cell_nbank_p2p_fraud}</td>
							<td>${sl_lm_cell_nbank_p2p_fraud}</td>
						</tr>
						<tr>
							<th>非银-P2P高风险</th>
							<td>${sl_id_nbank_mc_lost}</td>
							<td>${sl_cell_nbank_mc_lost}</td>
							<td>${sl_lm_cell_nbank_mc_lost}</td>
						</tr>
						<tr>
							<th>非银-P2P拒绝</th>
							<td>${sl_id_nbank_p2p_refuse}</td>
							<td>${sl_cell_p2p_refuse}</td>
							<td>${sl_lm_cell_nbank_p2p_refuse}</td>
						</tr>
						<tr>
							<th>非银-小贷中风险</th>
							<td>${sl_id_nbank_mc_bad}</td>
							<td>${sl_cell_nbank_mc_bad}</td>
							<td>${sl_lm_cell_nbank_mc_bad}</td>
						</tr>
						<tr>
							<th>非银-小贷一般风险</th>
							<td>${sl_id_nbank_mc_overdue}</td>
							<td>${sl_cell_nbank_mc_overdue}</td>
							<td>${sl_lm_cell_nbank_mc_overdue}</td>
						</tr>
						<tr>
							<th>非银-小贷资信不佳</th>
							<td>${sl_id_nbank_mc_fraud}</td>
							<td>${sl_cell_nbank_mc_fraud}</td>
							<td>${sl_lm_cell_nbank_mc_fraud}</td>
						</tr>
						<tr>
							<th>非银-小贷高风险</th>
							<td>${sl_id_nbank_mc_lost}</td>
							<td>${sl_cell_nbank_mc_lost}</td>
							<td>${sl_lm_cell_nbank_mc_lost}</td>
						</tr>
						<tr>
							<th>非银-小贷拒绝</th>
							<td>${sl_id_nbank_mc_refuse}</td>
							<td>${sl_cell_nbank_mc_refuse}</td>
							<td>${sl_lm_cell_nbank_mc_refuse}</td>
						</tr>
						<tr>
							<th>非银-现金类分期中风险</th>
							<td>${sl_id_nbank_ca_bad}</td>
							<td>${sl_cell_nbank_ca_bad}</td>
							<td>${sl_lm_cell_nbank_ca_bad}</td>
						</tr>
						<tr>
							<th>非银-现金类分期一般风险</th>
							<td>${sl_id_nbank_ca_overdue}</td>
							<td>${sl_cell_nbank_ca_overdue}</td>
							<td>${sl_lm_cell_nbank_ca_overdue}</td>
						</tr>
						<tr>
							<th>非银-现金类分期资信不佳</th>
							<td>${sl_id_nbank_ca_fraud}</td>
							<td>${sl_cell_nbank_ca_fraud}</td>
							<td>${sl_lm_cell_nbank_ca_fraud}</td>
						</tr>
						<tr>
							<th>非银-现金类分期高风险</th>
							<td>${sl_id_nbank_ca_lost}</td>
							<td>${sl_cell_nbank_ca_lost}</td>
							<td>${sl_lm_cell_nbank_ca_lost}</td>
						</tr>
						<tr>
						    <th>非银-现金类分期拒绝</th>
							<td>${sl_id_nbank_ca_refuse}</td>
							<td>${sl_cell_nbank_ca_refuse}</td>
							<td>${sl_lm_cell_nbank_ca_refuse}</td>
						</tr>
						<tr>
							<th>非银-代偿类分期中风险</th>
							<td>${sl_id_nbank_com_bad}</td>
							<td>${sl_cell_nbank_com_bad}</td>
							<td>${sl_lm_cell_nbank_com_bad}</td>
						</tr>
						<tr>
							<th>非银-代偿类分期一般风险</th>
							<td>${sl_id_nbank_com_overdue}</td>
							<td>${sl_cell_nbank_com_overdue}</td>
							<td>${sl_lm_cell_nbank_com_overdue}</td>
						</tr>
						<tr>
							<th>非银-代偿类分期资信不佳</th>
							<td>${sl_id_nbank_com_fraud}</td>
							<td>${sl_cell_nbank_com_fraud}</td>
							<td>${sl_lm_cell_nbank_com_fraud}</td>
						</tr>
						<tr>
							<th>非银-代偿类分期高风险</th>
							<td>${sl_id_nbank_com_lost}</td>
							<td>${sl_cell_nbank_com_lost}</td>
							<td>${sl_lm_cell_nbank_com_lost}</td>
						</tr>
						<tr>
							<th>非银-代偿类分期拒绝</th>
							<td>${sl_id_nbank_com_refuse}</td>
							<td>${sl_cell_nbank_com_refuse}</td>
							<td>${sl_lm_cell_nbank_com_refuse}</td>
						</tr>
						<tr>
							<th>非银-消费类分期中风险</th>
							<td>${sl_id_nbank_cf_bad}</td>
							<td>${sl_cell_nbank_cf_bad}</td>
							<td>${sl_lm_cell_nbank_cf_bad}</td>
						</tr>
						<tr>
							<th>非银-消费类分期一般风险</th>
							<td>${sl_id_nbank_cf_overdue}</td>
							<td>${sl_cell_nbank_cf_overdue}</td>
							<td>${sl_lm_cell_nbank_cf_overdue}</td>
						</tr>
						<tr>
							<th>非银-消费类分期资信不佳</th>
							<td>${sl_id_nbank_cf_fraud}</td>
							<td>${sl_cell_nbank_cf_fraud}</td>
							<td>${sl_lm_cell_nbank_cf_fraud}</td>
						</tr>
						<tr>
							<th>非银-消费类分期高风险</th>
							<td>${sl_id_nbank_cf_lost}</td>
							<td>${sl_cell_nbank_cf_lost}</td>
							<td>${sl_lm_cell_nbank_cf_lost}</td>
						</tr>
						<tr>
							<th>非银-消费类分期拒绝</th>
							<td>${sl_id_nbank_cf_refuse}</td>
							<td>${sl_cell_nbank_cf_refuse}</td>
							<td>${sl_lm_cell_nbank_cf_refuse}</td>
						</tr>
						<tr>
							<th>非银-其他中风险</th>
							<td>${sl_id_nbank_other_bad}</td>
							<td>${sl_cell_nbank_other_bad}</td>
							<td>${sl_lm_cell_nbank_other_bad}</td>
						</tr>
						<tr>
							<th>非银-其他一般风险</th>
							<td>${sl_id_nbank_other_overdue}</td>
							<td>${sl_cell_nbank_other_overdue}</td>
							<td>${sl_lm_cell_nbank_other_overdue}</td>
						</tr>
						<tr>
							<th>非银-其他资信不佳</th>
							<td>${sl_id_nbank_other_fraud}</td>
							<td>${sl_cell_nbank_other_fraud}</td>
							<td>${sl_lm_cell_nbank_other_fraud}</td>
						</tr>
						<tr>
							<th>非银-其他高风险</th>
							<td>${sl_id_nbank_other_lost}</td>
							<td>${sl_cell_nbank_other_lost}</td>
							<td>${sl_lm_cell_nbank_other_lost}</td>
						</tr>
						<tr>
							<th>非银-其他拒绝</th>
							<td>${sl_id_nbank_other_refuse}</td>
							<td>${sl_cell_nbank_other_refuse}</td>
							<td>${sl_lm_cell_nbank_other_refuse}</td>
						</tr>
					</tbody>
				 </table>
				</div>
			</div>
		</div>
	</div>
</body>
</html>